micronaut:
  h2:
    console:
      enabled: true
      path: '/h2'
  server:
    port: ${SERVICE_PORT:8080}
    cors:
      enabled: true
  application:
    name: productRth
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: update
    dialect: H2
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
    packages-to-scan:
      - 'com'
    entity-scan:
      packages: 'com.entities'
liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
endpoints:
  liquibase:
    enabled: true
    sensitive: false